global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'app1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app1:8080']

  - job_name: 'app2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app2:8080']

  - job_name: 'monitoring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['monitoring:8080']
  - job_name: 'controller'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['controller:8080']